### ISSUE TITLE
修改建议

### ISSUE THREAD

**Issue by NishizakiHayato** [aiheihe/WeNeedHome#1]
1.将地图变为平面
2.将模糊的边缘清晰化。
类似[中国地震台网](https://news.ceic.ac.cn/)的展示效果可能会更好。

**Comment by aiheihe** [comment]
用鼠标右键可以把调整地图的倾斜角度

> 1.将地图变为平面 2.将模糊的边缘清晰化。 类似[中国地震台网](https://news.ceic.ac.cn/)的展示效果可能会更好。

用鼠标右键可以把调整地图的倾斜角度
